[build-system]
requires = ["setuptools >= 80.9.0", "setuptools-scm >= 9.2", "wheel >= 0.45"]
build-backend = "setuptools.build_meta"

[project]
name = "pysmf"
requires-python = ">= 3.14"
readme = "README.md"
license = "Apache-2.0"
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/Mainframe-Renewal-Project/smf_parser"
Issues = "https://github.com/Mainframe-Renewal-Project/smf_parser/issues"

# This is required for dynamic versioning to work
[tool.setuptools_scm]
fallback_version = "0.0.0"
