# pyright: reportMissingImports=false

from __future__ import annotations

import re
from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any

from setuptools import Extension, setup
from setuptools._distutils.ccompiler import CompileError, new_compiler
from setuptools._distutils.sysconfig import customize_compiler
from setuptools._distutils.util import get_platform
from setuptools.command.build_ext import build_ext as build_ext_base
from setuptools.command.build_py import build_py as build_py_base
from wheel.bdist_wheel import bdist_wheel as bdist_wheel_base

DEFAULT_INCLUDE_DIR = Path("/usr/include/zos")
DEFAULT_IBM_INCLUDE_DIR = Path("/usr/include/IBM")
ROOT = Path(__file__).parent
HEADER_COMPILE_FLAGS = ("-Wno-trigraphs",)
FIELD_RE = re.compile(
    r"^\s*(?P<type>unsigned\s+char|char|u?int(?:8|16|32|64)_t|int(?:8|16|32|64)_t)"
    r"\s+(?P<name>[A-Za-z_]\w*)"
    r"(?:\[(?P<array>\d+)\])?"
    r"(?:\s*:\s*(?P<bits>\d+))?\s*;"
)


class BuildPy(build_py_base):
    def run(self) -> None:
        compiled_headers = _compile_headers(_include_dir())
        super().run()
        self._write_compiled_header_manifest(compiled_headers)

    def _write_compiled_header_manifest(
        self, compiled_headers: list[dict[str, object]]
    ) -> None:
        package_dir = Path(self.build_lib, "pysmf")
        package_dir.mkdir(parents=True, exist_ok=True)
        manifest = package_dir / "_compiled_headers.py"
        manifest.write_text(
            "# Generated by setup.py during package build.\n"
            "from __future__ import annotations\n\n"
            f"INCLUDE_DIR = {str(_include_dir())!r}\n"
            f"HEADERS = {compiled_headers!r}\n",
            encoding="utf-8",
        )


class BdistWheel(bdist_wheel_base):
    def finalize_options(self) -> None:
        super().finalize_options()
        self.root_is_pure = False

    def get_tag(self) -> tuple[str, str, str]:
        python_tag, abi_tag, platform_tag = super().get_tag()
        if platform_tag == "any":
            platform_tag = get_platform().replace("-", "_").replace(".", "_")
        return python_tag, abi_tag, platform_tag


class BuildExt(build_ext_base):
    def build_extensions(self) -> None:
        generated_source = _generate_record_parser_source(
            Path(self.build_temp), _include_dirs()
        )
        for extension in self.extensions:
            if extension.name == "pysmf._native":
                extension.sources.append(str(generated_source))
        super().build_extensions()


def _include_dir() -> Path:
    from os import environ

    configured = environ.get("PYSMF_ZOS_INCLUDE")
    if configured:
        return Path(configured)
    return DEFAULT_INCLUDE_DIR


def _include_dirs() -> tuple[Path, ...]:
    from os import environ

    include_dir = _include_dir()
    include_dirs = [include_dir]
    configured_ibm_include = environ.get("PYSMF_IBM_INCLUDE")
    ibm_include_dir = (
        Path(configured_ibm_include)
        if configured_ibm_include
        else include_dir.parent / "IBM"
    )
    if ibm_include_dir != include_dir:
        include_dirs.append(ibm_include_dir)
    include_root = include_dir.parent
    if include_root not in include_dirs:
        include_dirs.append(include_root)
    return tuple(include_dirs)


def _compile_headers(include_dir: Path) -> list[dict[str, object]]:
    if not include_dir.is_dir():
        raise RuntimeError(f"z/OS C header directory does not exist: {include_dir}")

    include_dirs = _include_dirs()
    compiler = new_compiler()
    customize_compiler(compiler)
    compiled: list[dict[str, object]] = []
    failures: list[str] = []

    with TemporaryDirectory() as source_dir_name:
        source_dir = Path(source_dir_name)
        for target in _header_targets():
            header_name = str(target["name"])
            resolved = _resolve_header(target, include_dirs)
            if resolved is None:
                continue
            include_name, header_path = resolved
            source = source_dir / f"compile_{header_path.stem.lower()}.c"
            source.write_text(
                f"#include <{include_name}>\nint main(void) {{ return 0; }}\n",
                encoding="utf-8",
            )
            try:
                compiler.compile(
                    [str(source)],
                    include_dirs=[str(path) for path in include_dirs],
                    extra_postargs=list(HEADER_COMPILE_FLAGS),
                )
            except CompileError as error:
                failures.append(f"{header_name} ({include_name}): {error}")
                continue
            compiled.append(
                {
                    "name": header_name,
                    "path": str(header_path),
                    "record_types": tuple(target["record_types"]),
                    "generic": bool(target["generic"]),
                }
            )

    if not any(header["generic"] for header in compiled):
        detail = "\n".join(failures)
        message = f"no generic SMF C header compiled from {include_dir}"
        if detail:
            message = f"{message}:\n{detail}"
        raise RuntimeError(message)
    return compiled


def _resolve_header(
    target: dict[str, Any], include_dirs: tuple[Path, ...]
) -> tuple[str, Path] | None:
    for header_name in _header_name_candidates(target):
        for include_dir in include_dirs:
            header_path = include_dir / header_name
            if header_path.is_file():
                return header_name, header_path
    return None


def _header_name_candidates(target: dict[str, Any]) -> tuple[str, ...]:
    header_names = (
        str(target["name"]),
        *(str(name) for name in target.get("alternate_names", ())),
    )
    candidates: list[str] = []
    for header_name in header_names:
        path = Path(header_name)
        stem = path.stem if path.suffix else header_name
        candidates.extend((header_name, stem, stem.upper()))
    return tuple(dict.fromkeys(candidates))


def _header_targets() -> tuple[dict[str, Any], ...]:
    registry_path = ROOT / "src" / "pysmf" / "_header_registry.py"
    spec = spec_from_file_location("_pysmf_header_registry", registry_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not load header registry from {registry_path}")
    module = module_from_spec(spec)
    spec.loader.exec_module(module)
    return tuple(module.HEADER_TARGETS)


def _native_extension() -> Extension:
    return Extension(
        "pysmf._native",
        sources=["src/pysmf/_native.c"],
        include_dirs=[str(path) for path in _include_dirs()],
        extra_compile_args=list(HEADER_COMPILE_FLAGS),
    )


def _generate_record_parser_source(
    build_temp: Path, include_dirs: tuple[Path, ...]
) -> Path:
    build_temp.mkdir(parents=True, exist_ok=True)
    source = build_temp / "_generated_records.c"
    records = _record_structs(include_dirs)

    includes = tuple(dict.fromkeys(record["include"] for record in records))
    lines = [
        "#define PY_SSIZE_T_CLEAN",
        "#include <Python.h>",
        "#include <stdint.h>",
        *(f"#include <{include}>" for include in includes),
        "",
        "static int set_long(PyObject *dict, const char *key, long long value) {",
        "    PyObject *object = PyLong_FromLongLong(value);",
        "    int result;",
        "    if (object == NULL) { return -1; }",
        "    result = PyDict_SetItemString(dict, key, object);",
        "    Py_DECREF(object);",
        "    return result;",
        "}",
        "",
        "static int set_bytes(PyObject *dict, const char *key, "
        "const unsigned char *data, Py_ssize_t length) {",
        "    PyObject *object = PyBytes_FromStringAndSize((const char *)data, length);",
        "    int result;",
        "    if (object == NULL) { return -1; }",
        "    result = PyDict_SetItemString(dict, key, object);",
        "    Py_DECREF(object);",
        "    return result;",
        "}",
        "",
        "static unsigned long long read_unsigned_be(const unsigned char *data, ",
        "Py_ssize_t length) {",
        "    unsigned long long value = 0;",
        "    Py_ssize_t index;",
        "    for (index = 0; index < length; index++) {",
        "        value = (value << 8) | data[index];",
        "    }",
        "    return value;",
        "}",
        "",
        "static long long read_signed_be(const unsigned char *data, ",
        "Py_ssize_t length) {",
        "    unsigned long long value = read_unsigned_be(data, length);",
        "    unsigned long long sign_bit;",
        "    if (length <= 0 || length >= (Py_ssize_t)sizeof(unsigned long long)) {",
        "        return (long long)value;",
        "    }",
        "    sign_bit = 1ULL << ((length * 8) - 1);",
        "    if (value & sign_bit) {",
        "        value |= (~0ULL) << (length * 8);",
        "    }",
        "    return (long long)value;",
        "}",
        "",
        "static int validate_record_type(const unsigned char *data, int expected) {",
        "    return data[5] == (unsigned char)expected;",
        "}",
        "",
    ]

    for record in records:
        lines.extend(_record_parser_function(record))

    lines.extend(
        [
            "PyObject *generated_parse_record(PyObject *self, PyObject *args) {",
            "    int record_type;",
            "    Py_buffer view;",
            "    PyObject *result;",
            "    if (!PyArg_ParseTuple(args, \"iy*\", &record_type, &view)) { "
            "return NULL; }",
            "    switch (record_type) {",
            *(
                f"    case {record['record_type']}: result = "
                f"parse_{record['struct_name']}(&view); break;"
                for record in records
            ),
            "    default:",
            "        PyBuffer_Release(&view);",
            "        PyErr_Format(PyExc_NotImplementedError, \"SMF type %d "
            "does not yet have a generated structured parser\", record_type);",
            "        return NULL;",
            "    }",
            "    PyBuffer_Release(&view);",
            "    return result;",
            "}",
            "",
        ]
    )
    source.write_text("\n".join(lines), encoding="utf-8")
    return source


def _record_structs(include_dirs: tuple[Path, ...]) -> list[dict[str, object]]:
    records: list[dict[str, object]] = []
    seen_record_types: set[int] = set()
    for target in _header_targets():
        resolved = _resolve_header(target, include_dirs)
        if resolved is None:
            continue
        include_name, header_path = resolved
        header_text = _read_header_text(header_path)
        structs = _header_structs(header_text)
        for record_type in target["record_types"]:
            if record_type in seen_record_types:
                continue
            struct_name = _record_struct_name(int(record_type), structs)
            if struct_name is None:
                continue
            fields = _record_struct_fields(structs[struct_name])
            if not fields:
                continue
            records.append(
                {
                    "record_type": int(record_type),
                    "struct_name": struct_name,
                    "include": include_name,
                    "fields": fields,
                }
            )
            seen_record_types.add(int(record_type))
    return records


def _read_header_text(header_path: Path) -> str:
    data = header_path.read_bytes()
    for encoding in ("utf-8", "cp1047", "latin-1"):
        try:
            return data.decode(encoding)
        except UnicodeDecodeError:
            continue
    return data.decode("latin-1", errors="ignore")


def _header_structs(header_text: str) -> dict[str, str]:
    structs: dict[str, str] = {}
    position = 0
    while True:
        match = re.search(r"struct\s+([A-Za-z_]\w*)\s*\{", header_text[position:])
        if match is None:
            return structs
        name = match.group(1)
        start = position + match.end()
        depth = 1
        index = start
        while index < len(header_text) and depth:
            if header_text[index] == "{":
                depth += 1
            elif header_text[index] == "}":
                depth -= 1
            index += 1
        if depth == 0:
            structs[name] = header_text[start : index - 1]
        position = index


def _record_struct_name(record_type: int, structs: dict[str, str]) -> str | None:
    candidates = (
        f"smfrcd{record_type:02d}",
        f"smfrcd{record_type}",
        f"smf{record_type}",
    )
    for candidate in candidates:
        if candidate in structs:
            return candidate
    return None


def _record_struct_fields(body: str) -> tuple[dict[str, object], ...]:
    fields: list[dict[str, object]] = []
    seen: set[str] = set()
    bit_offset = 0
    for raw_line in body.splitlines():
        if not raw_line.startswith("  ") or raw_line.startswith("    "):
            continue
        line = raw_line.split("/*", maxsplit=1)[0].strip()
        match = FIELD_RE.match(line)
        if match is None:
            continue
        name = match.group("name")
        c_type = " ".join(match.group("type").split())
        array_length = int(match.group("array")) if match.group("array") else 0
        field_bits = int(match.group("bits")) if match.group("bits") else 0
        if match.group("array") and array_length == 0:
            continue
        if name in seen or name.endswith(("_end_v1", "_end_v2", "_end_v3")):
            continue
        if field_bits:
            offset = bit_offset // 8
            bit_offset += field_bits
            if offset * 8 != bit_offset - field_bits or field_bits % 8:
                continue
            size = field_bits // 8
        else:
            if bit_offset % 8:
                bit_offset += 8 - (bit_offset % 8)
            offset = bit_offset // 8
            size = _c_field_size(c_type) * (array_length or 1)
            bit_offset += size * 8
        fields.append(
            {
                "name": name,
                "type": c_type,
                "array": array_length,
                "bits": field_bits,
                "offset": offset,
                "size": size,
                "signed": _c_field_is_signed(c_type),
            }
        )
        seen.add(name)
    return tuple(fields)


def _c_field_size(c_type: str) -> int:
    return {
        "char": 1,
        "unsigned char": 1,
        "uint8_t": 1,
        "int8_t": 1,
        "uint16_t": 2,
        "int16_t": 2,
        "uint32_t": 4,
        "int32_t": 4,
        "uint64_t": 8,
        "int64_t": 8,
    }[c_type]


def _c_field_is_signed(c_type: str) -> bool:
    return c_type.startswith("int") or c_type == "char"


def _record_parser_function(record: dict[str, object]) -> list[str]:
    struct_name = str(record["struct_name"])
    record_type = int(record["record_type"])
    minimum_size = max(
        int(field["offset"]) + int(field["size"]) for field in record["fields"]
    )
    lines = [
        f"static PyObject *parse_{struct_name}(Py_buffer *view) {{",
        "    const unsigned char *data;",
        "    PyObject *result;",
        f"    if (view->len < (Py_ssize_t){minimum_size}) {{",
        f"        PyErr_SetString(PyExc_ValueError, \"SMF type {record_type} "
        "record is shorter than its fixed C header structure\");",
        "        return NULL;",
        "    }",
        "    data = (const unsigned char *)view->buf;",
        f"    if (!validate_record_type(data, {record_type})) {{",
        f"        PyErr_SetString(PyExc_ValueError, \"SMF type {record_type} "
        "structured parser received bytes with the wrong record type\");",
        "        return NULL;",
        "    }",
        "    result = PyDict_New();",
        "    if (result == NULL) { return NULL; }",
    ]
    for field in record["fields"]:
        field_name = str(field["name"])
        offset = int(field["offset"])
        size = int(field["size"])
        if int(field["array"]):
            lines.extend(
                [
                    f"    if (set_bytes(result, \"{field_name}\", "
                    f"data + {offset}, (Py_ssize_t){size}) < 0) {{",
                    "        Py_DECREF(result);",
                    "        return NULL;",
                    "    }",
                ]
            )
        else:
            reader = "read_signed_be" if bool(field["signed"]) else "read_unsigned_be"
            lines.extend(
                [
                    f"    if (set_long(result, \"{field_name}\", "
                    f"{reader}(data + {offset}, (Py_ssize_t){size})) < 0) {{",
                    "        Py_DECREF(result);",
                    "        return NULL;",
                    "    }",
                ]
            )
    lines.extend(["    return result;", "}", ""])
    return lines


setup(
    cmdclass={"build_ext": BuildExt, "build_py": BuildPy, "bdist_wheel": BdistWheel},
    ext_modules=[_native_extension()],
)
