# pyright: reportMissingImports=false

from __future__ import annotations

from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any

from setuptools import Extension, setup
from setuptools._distutils.ccompiler import CompileError, new_compiler
from setuptools._distutils.sysconfig import customize_compiler
from setuptools._distutils.util import get_platform
from setuptools.command.build_py import build_py as build_py_base
from wheel.bdist_wheel import bdist_wheel as bdist_wheel_base

DEFAULT_INCLUDE_DIR = Path("/usr/include/zos")
ROOT = Path(__file__).parent
HEADER_COMPILE_FLAGS = ("-Wno-trigraphs",)


class build_py(build_py_base):
    def run(self) -> None:
        compiled_headers = _compile_headers(_include_dir())
        super().run()
        self._write_compiled_header_manifest(compiled_headers)

    def _write_compiled_header_manifest(self, compiled_headers: list[dict[str, object]]) -> None:
        package_dir = Path(self.build_lib, "smf_parser")
        package_dir.mkdir(parents=True, exist_ok=True)
        manifest = package_dir / "_compiled_headers.py"
        manifest.write_text(
            "# Generated by setup.py during package build.\n"
            "from __future__ import annotations\n\n"
            f"INCLUDE_DIR = {str(_include_dir())!r}\n"
            f"HEADERS = {compiled_headers!r}\n",
            encoding="utf-8",
        )


class bdist_wheel(bdist_wheel_base):
    def finalize_options(self) -> None:
        super().finalize_options()
        self.root_is_pure = False

    def get_tag(self) -> tuple[str, str, str]:
        python_tag, abi_tag, platform_tag = super().get_tag()
        if platform_tag == "any":
            platform_tag = get_platform().replace("-", "_").replace(".", "_")
        return python_tag, abi_tag, platform_tag


def _include_dir() -> Path:
    from os import environ

    configured = environ.get("SMF_PARSER_ZOS_INCLUDE")
    if configured:
        return Path(configured)
    return DEFAULT_INCLUDE_DIR


def _compile_headers(include_dir: Path) -> list[dict[str, object]]:
    if not include_dir.is_dir():
        raise RuntimeError(f"z/OS C header directory does not exist: {include_dir}")

    compiler = new_compiler()
    customize_compiler(compiler)
    compiled: list[dict[str, object]] = []
    failures: list[str] = []

    with TemporaryDirectory() as source_dir_name:
        source_dir = Path(source_dir_name)
        for target in _header_targets():
            header_name = str(target["name"])
            header_path = include_dir / header_name
            if not header_path.is_file():
                continue
            source = source_dir / f"compile_{header_path.stem}.c"
            source.write_text(f"#include <{header_name}>\nint main(void) {{ return 0; }}\n", encoding="utf-8")
            try:
                compiler.compile(
                    [str(source)],
                    include_dirs=[str(include_dir)],
                    extra_postargs=list(HEADER_COMPILE_FLAGS),
                )
            except CompileError as error:
                failures.append(f"{header_name}: {error}")
                continue
            compiled.append(
                {
                    "name": header_name,
                    "record_types": tuple(target["record_types"]),
                    "generic": bool(target["generic"]),
                }
            )

    if not any(header["generic"] for header in compiled):
        detail = "\n".join(failures)
        message = f"no generic SMF C header compiled from {include_dir}"
        if detail:
            message = f"{message}:\n{detail}"
        raise RuntimeError(message)
    return compiled


def _header_targets() -> tuple[dict[str, Any], ...]:
    registry_path = ROOT / "src" / "smf_parser" / "_header_registry.py"
    spec = spec_from_file_location("_smf_parser_header_registry", registry_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not load header registry from {registry_path}")
    module = module_from_spec(spec)
    spec.loader.exec_module(module)
    return tuple(module.HEADER_TARGETS)


def _native_extension() -> Extension:
    include_dir = _include_dir()
    return Extension(
        "smf_parser._native",
        sources=["src/smf_parser/_native.c"],
        include_dirs=[str(include_dir)],
        extra_compile_args=list(HEADER_COMPILE_FLAGS),
    )


setup(cmdclass={"build_py": build_py, "bdist_wheel": bdist_wheel}, ext_modules=[_native_extension()])
