"""z/OS SMF C headers that setup.py is expected to compile."""

from __future__ import annotations

from typing import Iterable


def _target(
    name: str,
    record_types: Iterable[int],
    *,
    generic: bool,
    alternate_names: tuple[str, ...] = (),
) -> dict[str, object]:
    target = {
        "name": name,
        "record_types": tuple(record_types),
        "generic": generic,
    }
    if alternate_names:
        target["alternate_names"] = alternate_names
    return target

# ``generic=True`` means the compiled header backs generic SMF record boundary
# and common-header parsing. Type-specific wrappers can be added from the same
# registry without changing the runtime discovery contract.
HEADER_TARGETS = (
    _target("ifasmfh.h", (), generic=True),
    _target("ifasmfr.h", range(7), generic=True),
    _target(
        "csfsm82c.h",
        (82,),
        generic=False,
        alternate_names=("CSFSM82C",),
    ),
    *(
        _target(name, range(start, stop), generic=False)
        for name, start, stop in (
            ("ifasmfr1.h", 7, 20),
            ("ifasmfr2.h", 20, 28),
            ("ifasmfr3.h", 28, 37),
            ("ifasmfr4.h", 37, 47),
            ("ifasmfr5.h", 47, 55),
            ("ifasmfr9.h", 80, 84),
            ("ifasmfra.h", 85, 104),
        )
    ),
    *(
        _target(name, record_types, generic=False)
        for name, record_types in (
            ("ifgsmf14.h", (14,)),
            ("iggsmf17.h", (17,)),
            ("iggsmf18.h", (18,)),
            ("iggsmf19.h", (19,)),
            ("igesmf21.h", (21,)),
            ("iosdsmfr.h", (22,)),
            ("iazsmf24.h", (24,)),
            ("iazsmf25.h", (25,)),
            ("iazsmf26.h", (26,)),
            ("itvsmf41.h", (41,)),
            ("igwsmf.h", (42,)),
            ("iazsmf43.h", (43,)),
            ("iazsmf45.h", (45,)),
            ("iazsmf47.h", (47,)),
            ("iazsmf48.h", (48,)),
            ("iazsmf49.h", (49,)),
            ("iazsmf52.h", (52,)),
            ("iazsmf53.h", (53,)),
            ("iazsmf54.h", (54,)),
            ("iazsmf55.h", (55,)),
            ("iazsmf56.h", (56,)),
            ("iazsmf57.h", (57,)),
            ("iazsmf58.h", (58,)),
            ("idasmf62.h", (60, 61, 62)),
            ("idasmf64.h", (64,)),
            ("iazsmf84.h", (84,)),
            ("cbrsmf.h", (85,)),
            ("isgysmfr.h", (87,)),
            ("ixgsmf88.h", (88,)),
        )
    ),
    *(
        _target(name, (90,), generic=False)
        for name in (
            "ifbsmf90.h",
            "cnzmysmf.h",
            "cnzmysm2.h",
            "csvdlsmf.h",
            "csvapsmf.h",
            "csvlpsmf.h",
            "ihavbsmf.h",
            "ixcysm90.h",
        )
    ),
    _target(
        "iefopsmf.h",
        (90,),
        generic=False,
        alternate_names=("IEFOPSMF",),
    ),
    *(
        _target(name, record_types, generic=False)
        for name, record_types in (
            ("bpxysmfr.h", (92,)),
            ("iecsmf94.h", (94,)),
            ("iwmsmf90.h", (97,)),
            ("iwmsmf97.h", (97,)),
            ("ihahr098.h", (98,)),
            ("ihahr981.h", (98,)),
            ("iggindvx.h", (98,)),
            ("iggindvs.h", (98,)),
            ("iggindbs.h", (98,)),
            ("iggindbx.h", (98,)),
            ("hwismf6a.h", (106,)),
            ("hisysmfr.h", (113,)),
            ("ezasmf.h", (119,)),
            ("iosds124.h", (124,)),
            ("gtzzsmf1.h", (125,)),
            ("ifasmfcn.h", (30, 1154)),
            ("iazs1153.h", (1153,)),
            ("ifar1154.h", (1154,)),
            ("iazs1154.h", (1154,)),
            ("ifas4128.h", (1154,)),
            ("csvs1156.h", (1156,)),
            ("iosds983.h", (98, 983)),
            ("iosds984.h", (98, 984)),
        )
    ),
)

# Extra record-specific parser metadata consumed by tools/smf_build.py.
# Only keep explicit names that cannot be inferred from action payload fields.
_EXPLICIT_SPECIAL_RECORD_STRUCT_NAMES: dict[int, tuple[str, ...]] = {}

SPECIAL_RECORD_ACTIONS = {
    41: (
        {
            "kind": "inline_long_triplet_directory",
            "key": "relocate_sections",
            "directory_field": "smf41opd",
            "count_field": "smf41trp",
        },
    ),
    42: (
        {
            "kind": "inline_long_triplet_directory",
            "key": "relocate_sections",
            "directory_field": "smf42ops",
            "count_field": "smf42nt",
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 1,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42s1",
            "required_subtype_names": (
                "smf42bmo",
                "smf42bml",
                "smf42bmn",
            ),
            "triplet_count_name": "smf42bmn",
            "triplet_length_name": "smf42bml",
            "triplet_directory_name": "smf42bmo",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 16,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 2,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42s2",
            "required_subtype_names": (
                "smf42cuo",
                "smf42cul",
                "smf42cun",
            ),
            "triplet_count_name": "smf42cun",
            "triplet_length_name": "smf42cul",
            "triplet_directory_name": "smf42cuo",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 16,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 3,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42s3",
            "required_subtype_names": (
                "smf42eao",
                "smf42eal",
                "smf42ean",
            ),
            "triplet_count_name": "smf42ean",
            "triplet_length_name": "smf42eal",
            "triplet_directory_name": "smf42eao",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 8,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 4,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42s4",
            "required_subtype_names": (
                "smf42cco",
                "smf42ccl",
                "smf42ccn",
            ),
            "triplet_count_name": "smf42ccn",
            "triplet_length_name": "smf42ccl",
            "triplet_directory_name": "smf42cco",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 24,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 5,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42s5",
            "required_subtype_names": (
                "smf42sro",
                "smf42srl",
                "smf42srn",
            ),
            "triplet_count_name": "smf42srn",
            "triplet_length_name": "smf42srl",
            "triplet_directory_name": "smf42sro",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 16,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 6,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42s6",
            "required_subtype_names": (
                "smf42jho",
                "smf42jhl",
                "smf42jhn",
            ),
            "triplet_count_name": "smf42jhn",
            "triplet_length_name": "smf42jhl",
            "triplet_directory_name": "smf42jho",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 8,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 9,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42s9",
            "required_subtype_names": (
                "smf42abo",
                "smf42abl",
                "smf42abn",
            ),
            "triplet_count_name": "smf42abn",
            "triplet_length_name": "smf42abl",
            "triplet_directory_name": "smf42abo",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 16,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 10,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42sa",
            "required_subtype_names": (
                "smf42vsf",
                "smf42vsl",
                "smf42vsn",
            ),
            "triplet_count_name": "smf42vsn",
            "triplet_length_name": "smf42vsl",
            "triplet_directory_name": "smf42vsf",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 8,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 11,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42sb",
            "required_subtype_names": (
                "smf42xro",
                "smf42xrl",
                "smf42xrn",
            ),
            "triplet_count_name": "smf42xrn",
            "triplet_length_name": "smf42xrl",
            "triplet_directory_name": "smf42xro",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 8,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 15,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42sf",
            "required_subtype_names": (
                "smf42fc1",
                "smf42fc2",
                "smf42fc3",
            ),
            "triplet_count_name": "smf42fc3",
            "triplet_length_name": "smf42fc2",
            "triplet_directory_name": "smf42fc1",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 16,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 15,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42sf",
            "required_subtype_names": (
                "smf42afc1",
                "smf42afc2",
                "smf42afc3",
            ),
            "triplet_count_name": "smf42afc3",
            "triplet_length_name": "smf42afc2",
            "triplet_directory_name": "smf42afc1",
            "directory_key": "above_bar_relocate_sections",
            "minimum_section_length": 32,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 16,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42sg",
            "required_subtype_names": (
                "smf42gd1",
                "smf42gd2",
                "smf42gd3",
            ),
            "triplet_count_name": "smf42gd3",
            "triplet_length_name": "smf42gd2",
            "triplet_directory_name": "smf42gd1",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 16,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 16,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42sg",
            "required_subtype_names": (
                "smf42agd1",
                "smf42agd2",
                "smf42agd3",
            ),
            "triplet_count_name": "smf42agd3",
            "triplet_length_name": "smf42agd2",
            "triplet_directory_name": "smf42agd1",
            "directory_key": "above_bar_relocate_sections",
            "minimum_section_length": 32,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 17,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42sh",
            "required_subtype_names": (
                "smf42hl1",
                "smf42hl2",
                "smf42hl3",
            ),
            "triplet_count_name": "smf42hl3",
            "triplet_length_name": "smf42hl2",
            "triplet_directory_name": "smf42hl1",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 16,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 18,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42si",
            "required_subtype_names": (
                "smf42im1",
                "smf42im2",
                "smf42im3",
            ),
            "triplet_count_name": "smf42im3",
            "triplet_length_name": "smf42im2",
            "triplet_directory_name": "smf42im1",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 24,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 19,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42sj",
            "required_subtype_names": (
                "smf42jn1",
                "smf42jn2",
                "smf42jn3",
            ),
            "triplet_count_name": "smf42jn3",
            "triplet_length_name": "smf42jn2",
            "triplet_directory_name": "smf42jn1",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 16,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 19,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42sj",
            "required_subtype_names": (
                "smf42ajn1",
                "smf42ajn2",
                "smf42ajn3",
            ),
            "triplet_count_name": "smf42ajn3",
            "triplet_length_name": "smf42ajn2",
            "triplet_directory_name": "smf42ajn1",
            "directory_key": "above_bar_relocate_sections",
            "minimum_section_length": 32,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 20,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42sk",
            "required_subtype_names": (
                "smf42kn1",
                "smf42kn2",
                "smf42kn3",
            ),
            "triplet_count_name": "smf42kn3",
            "triplet_length_name": "smf42kn2",
            "triplet_directory_name": "smf42kn1",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 16,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 21,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42sl",
            "required_subtype_names": (
                "smf42ln1",
                "smf42ln2",
                "smf42ln3",
            ),
            "triplet_count_name": "smf42ln3",
            "triplet_length_name": "smf42ln2",
            "triplet_directory_name": "smf42ln1",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 24,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 22,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42sm",
            "required_subtype_names": (
                "smf4222aud",
                "smf4222lad",
                "smf4222nad",
            ),
            "triplet_count_name": "smf4222nad",
            "triplet_length_name": "smf4222lad",
            "triplet_directory_name": "smf4222aud",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 16,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 23,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42sn",
            "required_subtype_names": (
                "smf4223sec",
                "smf4223lsc",
                "smf4223nsc",
            ),
            "triplet_count_name": "smf4223nsc",
            "triplet_length_name": "smf4223lsc",
            "triplet_directory_name": "smf4223sec",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 8,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 24,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42sp",
            "required_subtype_names": (
                "smf42pn1",
                "smf42pn2",
                "smf42pn3",
            ),
            "triplet_count_name": "smf42pn3",
            "triplet_length_name": "smf42pn2",
            "triplet_directory_name": "smf42pn1",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 24,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 25,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42sq",
            "required_subtype_names": (
                "smf42qn1",
                "smf42qn2",
                "smf42qn3",
            ),
            "triplet_count_name": "smf42qn3",
            "triplet_length_name": "smf42qn2",
            "triplet_directory_name": "smf42qn1",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 24,
        },
        {
            "kind": "subtype_struct_overlay_directory",
            "subtype_field_name": "smf42sty",
            "subtype_value": 27,
            "anchor_field_name": "smf42ops",
            "subtype_struct": "smf42s27",
            "required_subtype_names": (
                "smf4227r1",
                "smf4227r2",
                "smf4227r3",
            ),
            "triplet_count_name": "smf4227r3",
            "triplet_length_name": "smf4227r2",
            "triplet_directory_name": "smf4227r1",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 24,
        },
    ),
    80: (
        {
            "kind": "compact_section_directory_fallback",
            "key": "relocate_sections",
            "anchor_field": "smf80des",
            "relocate_field": "smf80evq",
            "relocate_shift": 1,
            "count_delta": 2,
        },
    ),
    83: (
        {
            "kind": "racf83_subtype1_security",
            "security_struct": "smf83ds1",
            "variable_section_struct": "smf83var",
            "subtype_value": 1,
            "sds_type_value": 3,
            "security_minimum_length": 96,
            "header_integer_fields": (
                ("smf83typ", "read_unsigned_be(data + smf83_subtype_offset, 2)"),
                ("smf83trp", "read_unsigned_be(data + smf83_sds_offset, 2)"),
                ("smf83opd", "read_unsigned_be(data + smf83_sds_offset + 4, 4)"),
                ("smf83lpd", "read_unsigned_be(data + smf83_sds_offset + 8, 2)"),
                ("smf83npd", "read_unsigned_be(data + smf83_sds_offset + 10, 2)"),
                ("smf83od1", "read_unsigned_be(data + smf83_sds_offset + 12, 4)"),
                ("smf83ld1", "read_unsigned_be(data + smf83_sds_offset + 16, 2)"),
                ("smf83nd1", "read_unsigned_be(data + smf83_sds_offset + 18, 2)"),
                ("smf83od2", "read_unsigned_be(data + smf83_sds_offset + 20, 4)"),
                ("smf83ld2", "read_unsigned_be(data + smf83_sds_offset + 24, 2)"),
                ("smf83nd2", "read_unsigned_be(data + smf83_sds_offset + 26, 2)"),
            ),
        },
    ),
    85: (
        {
            "kind": "offset_long_triplet_directory",
            "key": "extended_relocate_sections",
            "offset_field": "smf85oso",
            "count_field": "smf85osn",
            "length_field": "smf85osl",
        },
    ),
    98: (
        {
            "kind": "long_triplet_directory",
            "key": "relocate_sections",
            "directory": "fixed_end",
            "count_field": "smf98sdstripletsnum",
        },
        {
            "kind": "smf98_subtype_overlay",
            "subtype_value": 1,
            "subtype_field_name": "smf98sty",
            "data_offset_field_name": "smf98dof",
            "subtype_struct": "smf98_1_data",
            "required_record_names": (
                "smf98sty",
                "smf98dof",
            ),
            "required_subtype_names": (
                "smf98_1_datatripletsnum",
                "smf98_1_datatripletslen",
                "smf98_1_prioritybucketof",
            ),
            "triplet_count_name": "smf98_1_datatripletsnum",
            "triplet_length_name": "smf98_1_datatripletslen",
            "triplet_directory_name": "smf98_1_prioritybucketof",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 40,
        },
        {
            "kind": "smf98_subtype_overlay",
            "subtype_value": 3,
            "subtype_field_name": "smf98sty",
            "data_offset_field_name": "smf98dof",
            "subtype_struct": "smf98_3_data",
            "required_record_names": (
                "smf98sty",
                "smf98dof",
            ),
            "required_subtype_names": (
                "smf98_3_datatripletsnum",
                "smf98_3_datatripletslen",
                "smf98_3_dta_aggbkt1of",
            ),
            "triplet_count_name": "smf98_3_datatripletsnum",
            "triplet_length_name": "smf98_3_datatripletslen",
            "triplet_directory_name": "smf98_3_dta_aggbkt1of",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 40,
        },
        {
            "kind": "smf98_subtype_overlay",
            "subtype_value": 4,
            "subtype_field_name": "smf98sty",
            "data_offset_field_name": "smf98dof",
            "subtype_struct": "smf98_4_data",
            "required_record_names": (
                "smf98sty",
                "smf98dof",
            ),
            "required_subtype_names": (
                "smf98_4_datatripletsnum",
                "smf98_4_datatripletslen",
                "smf98_4_dta_aggbkt1of",
            ),
            "triplet_count_name": "smf98_4_datatripletsnum",
            "triplet_length_name": "smf98_4_datatripletslen",
            "triplet_directory_name": "smf98_4_dta_aggbkt1of",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 40,
        },
        {
            "kind": "smf98_subtype_overlay",
            "subtype_value": 7,
            "subtype_field_name": "smf98sty",
            "data_offset_field_name": "smf98dof",
            "subtype_struct": "smf98_7_data",
            "required_record_names": (
                "smf98sty",
                "smf98dof",
            ),
            "required_subtype_names": (
                "smf98_7_datatripletsnum",
                "smf98_7_datatripletslen",
                "smf98_7_bucket1of",
            ),
            "triplet_count_name": "smf98_7_datatripletsnum",
            "triplet_length_name": "smf98_7_datatripletslen",
            "triplet_directory_name": "smf98_7_bucket1of",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 40,
        },
        {
            "kind": "smf98_subtype_overlay",
            "subtype_value": 5,
            "subtype_field_name": "smf98sty",
            "data_offset_field_name": "smf98dof",
            "subtype_struct": "smf98_5_data",
            "required_record_names": (
                "smf98sty",
                "smf98dof",
            ),
            "required_subtype_names": (
                "smf98_5_datatripletsnum",
                "smf98_5_datatripletslen",
                "smf98_5_bucket1of",
            ),
            "triplet_count_name": "smf98_5_datatripletsnum",
            "triplet_length_name": "smf98_5_datatripletslen",
            "triplet_directory_name": "smf98_5_bucket1of",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 40,
        },
        {
            "kind": "smf98_subtype_overlay",
            "subtype_value": 6,
            "subtype_field_name": "smf98sty",
            "data_offset_field_name": "smf98dof",
            "subtype_struct": "smf98_6_data",
            "required_record_names": (
                "smf98sty",
                "smf98dof",
            ),
            "required_subtype_names": (
                "smf98_6_datatripletsnum",
                "smf98_6_datatripletslen",
                "smf98_6_bucket1of",
            ),
            "triplet_count_name": "smf98_6_datatripletsnum",
            "triplet_length_name": "smf98_6_datatripletslen",
            "triplet_directory_name": "smf98_6_bucket1of",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 40,
        },
        {
            "kind": "smf98_subtype_overlay",
            "subtype_value": 8,
            "subtype_field_name": "smf98sty",
            "data_offset_field_name": "smf98dof",
            "subtype_struct": "smf98_8_data",
            "required_record_names": (
                "smf98sty",
                "smf98dof",
            ),
            "required_subtype_names": (
                "smf98_8_datatripletsnum",
                "smf98_8_datatripletslen",
                "smf98_8_bucket1of",
            ),
            "triplet_count_name": "smf98_8_datatripletsnum",
            "triplet_length_name": "smf98_8_datatripletslen",
            "triplet_directory_name": "smf98_8_bucket1of",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 40,
        },
    ),
    113: (
        {
            "kind": "smf113_sds_overlay",
            "sds_struct": "smf113sds",
            "sds_length_field": "smf113sdl",
            "minimum_section_length": 24,
            "directory_key": "relocate_sections",
        },
    ),
    119: (
        {
            "kind": "smf119_ident_overlay",
            "triplet_struct": "SMF119SDefSect",
            "ident_struct": "SMF119Ident",
            "triplet_count_field": "SMF119SD_TRN",
            "ident_offset_field": "SMF119IDOff",
            "ident_length_field": "SMF119IDLen",
            "ident_count_field": "SMF119IDNum",
            "triplet_directory_anchor_field": "SMF119S3Off",
            "directory_key": "relocate_sections",
            "skip_ident_fields": ("SMF119TI_rsvd1", "SMF119TI_rsvd2"),
        },
    ),
    124: (
        {
            "kind": "conditional_offset_long_triplet_directory",
            "key": "relocate_sections",
            "subtype_field_name": "smf124sty",
            "subtype_value": 1,
            "offset_field": "smf124s1_port_offset",
            "count_field": "smf124s1_port_num",
            "length_field": "smf124s1_port_len",
        },
        {
            "kind": "conditional_offset_long_triplet_directory",
            "key": "relocate_sections",
            "subtype_field_name": "smf124sty",
            "subtype_value": 2,
            "offset_field": "smf124s2_epsecstat_offset",
            "count_field": "smf124s2_epsecstat_num",
            "length_field": "smf124s2_epsecstat_len",
        },
        {
            "kind": "conditional_offset_long_triplet_directory",
            "key": "relocate_sections",
            "subtype_field_name": "smf124sty",
            "subtype_value": 3,
            "offset_field": "smf124s3_authkeyupd_offset",
            "count_field": "smf124s3_authkeyupd_num",
            "length_field": "smf124s3_authkeyupd_len",
        },
        {
            "kind": "conditional_offset_long_triplet_directory",
            "key": "relocate_sections",
            "subtype_field_name": "smf124sty",
            "subtype_value": 4,
            "offset_field": "smf124s4_encrkeyupd_offset",
            "count_field": "smf124s4_encrkeyupd_num",
            "length_field": "smf124s4_encrkeyupd_len",
        },
        {
            "kind": "conditional_offset_long_triplet_directory",
            "key": "relocate_sections",
            "subtype_field_name": "smf124sty",
            "subtype_value": 5,
            "offset_field": "smf124s5_extkeymgrinfo_offset",
            "count_field": "smf124s5_extkeymgrinfo_num",
            "length_field": "smf124s5_extkeymgrinfo_len",
        },
    ),
    1154: (
        {
            "kind": "smf1154_common_overlay",
            "ctrp_struct": "smf1154_ctrp",
            "common_struct": "smf1154_c_hdr",
            "required_ctrp_names": (
                "smf1154_ctrp_trn",
                "smf1154_c_offset",
                "smf1154_c_length",
                "smf1154_c_number",
                "smf1154_subspec_offset",
                "smf1154_subspec_length",
                "smf1154_subspec_number",
            ),
            "common_directory_key": "relocate_sections",
            "subspec_directory_key": "extended_relocate_sections",
        },
        {
            "kind": "smf1154_subtype_overlay",
            "subtype_value": 128,
            "subtype_struct": "smf1154_128",
            "required_names": (
                "smf1154_128_trn",
                "smf1154_128_sds_length",
                "smf1154_128_crypctrs_offset",
                "smf1154_128_crypctrs_length",
                "smf1154_128_crypctrs_number",
            ),
            "triplet_offset_name": "smf1154_128_crypctrs_offset",
            "triplet_length_name": "smf1154_128_crypctrs_length",
            "triplet_number_name": "smf1154_128_crypctrs_number",
            "section_length_name": "smf1154_128_sds_length",
            "directory_key": "extended_relocate_sections",
            "minimum_section_length": 12,
        },
    ),
}


def _derive_special_record_struct_names(
    explicit_names: dict[int, tuple[str, ...]],
    actions: dict[int, tuple[dict[str, object], ...]],
) -> dict[int, tuple[str, ...]]:
    derived: dict[int, set[str]] = {
        record_type: set(names) for record_type, names in explicit_names.items()
    }
    for record_type, action_specs in actions.items():
        names = derived.setdefault(record_type, set())
        for action_spec in action_specs:
            for key in (
                "security_struct",
                "ctrp_struct",
                "common_struct",
                "triplet_struct",
                "ident_struct",
                "subtype_struct",
                "sds_struct",
            ):
                value = action_spec.get(key)
                if isinstance(value, str) and value:
                    names.add(value)
    return {
        record_type: tuple(sorted(names))
        for record_type, names in derived.items()
        if names
    }


SPECIAL_RECORD_STRUCT_NAMES = _derive_special_record_struct_names(
    _EXPLICIT_SPECIAL_RECORD_STRUCT_NAMES,
    SPECIAL_RECORD_ACTIONS,
)

# Optional per-record parser generation behavior toggles.
RECORD_TYPE_OPTIONS = {
    1154: {"allow_empty_fields": True},
}
